salesloft-exercise:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      dataset: dev-environment-2
      threads: 4
  target: prod
  outputs:
    dev:
      type: bigquery
      method: oauth
      dataset: salesloftexercise
      threads: 4