salesloft-exercise:
  target: dev
  #target: prod
  outputs:
    dev:
      type: bigquery
      method: oauth
      dataset: sales-loft-exercise
      threads: 4
  target: prod
  outputs:
    dev:
      type: bigquery
      method: oauth
      dataset: sales-loft-exercise
      threads: 4